version: '3.8'

services:
  zillow-scraper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-zillow-images}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    volumes:
      - .:/app
    restart: unless-stopped
